version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: pass12345
    networks:
      - mongo-compose-networks

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongo-compose-networks
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass12345
      ME_CONFIG_MONGODB_URL: mongodb://username:pass12345@mongo:27017/

networks:
  mongo-compose-networks:
    driver: bridge